import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  loginSurface: { flex: 1, backgroundColor: '#F7F8FC' }, loginContent: { flexGrow: 1, justifyContent: 'center', padding: 24 }, loginLogo: { width: 150, height: 130, alignSelf: 'center', marginBottom: 6 }, loginTitle: { color: '#1E293B', fontSize: 28, fontWeight: '800', textAlign: 'center' }, loginSubtitle: { color: '#64748B', fontSize: 15, textAlign: 'center', marginTop: 8, marginBottom: 24 }, loginCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, borderWidth: 1, borderColor: '#E2E8F0' }, loginModeRow: { flexDirection: 'row', gap: 8, marginTop: 4 }, loginNotice: { color: '#64748B', fontSize: 12, lineHeight: 17, marginTop: 14, textAlign: 'center' },
  safeArea: { flex: 1, backgroundColor: '#F7F8FC' }, darkSurface: { backgroundColor: '#252447' }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F7F8FC', padding: 32 }, splashLogo: { width: 230, height: 210 }, loadingText: { color: '#4B43CF', fontSize: 28, fontWeight: '800', marginTop: 2 }, loadingCaption: { color: '#64748B', fontSize: 14, marginTop: 8 },
  header: { padding: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderColor: '#E6E8F3' }, headerIdentity: { flexDirection: 'row', alignItems: 'center', gap: 8 }, headerLogo: { width: 48, height: 44 }, brand: { fontSize: 28, color: '#4B43CF', fontWeight: '800' }, subtitle: { color: '#64748B', marginTop: 2 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#E7E6FF', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#4B43CF', fontSize: 18, fontWeight: '800' },
  content: { padding: 18, paddingBottom: 40 }, sectionTitle: { fontSize: 15, fontWeight: '800', color: '#1E293B', marginTop: 12, marginBottom: 9 }, sessionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, logoutText: { color: '#4338CA', fontSize: 13, fontWeight: '800' }, navigation: { flexDirection: 'row', gap: 7, marginBottom: 8, flexWrap: 'wrap' },
  choice: { paddingVertical: 9, paddingHorizontal: 11, borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, backgroundColor: '#FFFFFF' }, choiceActive: { borderColor: '#4F46E5', backgroundColor: '#EEF2FF' }, choiceText: { color: '#475569', fontWeight: '700', fontSize: 12 }, choiceTextActive: { color: '#4338CA' },
  card: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#E2E8F0' }, cardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 }, cardTitle: { color: '#1E293B', fontSize: 17, fontWeight: '800' }, hint: { color: '#64748B', fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 10 }, muted: { color: '#64748B', fontSize: 13, marginTop: 3 },
  field: { marginTop: 10 }, label: { color: '#334155', fontSize: 13, fontWeight: '700', marginBottom: 6 }, input: { backgroundColor: '#F8FAFC', color: '#1E293B', borderWidth: 1, borderColor: '#CBD5E1', paddingHorizontal: 12, paddingVertical: 11, borderRadius: 10, fontSize: 15 },
  primaryButton: { backgroundColor: '#4F46E5', borderRadius: 10, alignItems: 'center', paddingVertical: 13, marginTop: 16 }, primaryButtonText: { color: '#FFFFFF', fontWeight: '800' }, actionRow: { flexDirection: 'row', gap: 8, marginTop: 14 }, approveButton: { flex: 1, backgroundColor: '#10B981', alignItems: 'center', paddingVertical: 10, borderRadius: 9 }, actionText: { color: '#FFFFFF', fontWeight: '800', fontSize: 13 }, rejectButton: { flex: 1, backgroundColor: '#FFF1F2', alignItems: 'center', paddingVertical: 10, borderRadius: 9 }, rejectText: { color: '#BE123C', fontWeight: '800', fontSize: 13 }, outlineButton: { marginTop: 14, borderWidth: 1, borderColor: '#FDA4AF', alignItems: 'center', paddingVertical: 10, borderRadius: 9 }, outlineText: { color: '#BE123C', fontWeight: '800', fontSize: 13 },
  badge: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, overflow: 'hidden', fontSize: 11, fontWeight: '800' }, badgePENDING: { color: '#92400E', backgroundColor: '#FEF3C7' }, badgeAPPROVED: { color: '#047857', backgroundColor: '#D1FAE5' }, badgeREJECTED: { color: '#BE123C', backgroundColor: '#FFE4E6' }, badgeREVOKED: { color: '#475569', backgroundColor: '#E2E8F0' },
  userChoices: { flexDirection: 'row', gap: 7, flexWrap: 'wrap', marginTop: 4 }, member: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 8 }, memberName: { color: '#1E293B', fontWeight: '800' }, memberDetail: { color: '#475569', fontSize: 13, marginTop: 5 }, ownerTag: { color: '#4338CA', fontWeight: '800', fontSize: 12 }, selectedCard: { borderColor: '#4F46E5', borderWidth: 2 }, activeTag: { color: '#047857', fontWeight: '800', fontSize: 12 }, removeText: { color: '#BE123C', fontWeight: '800', fontSize: 12 }, smallButton: { backgroundColor: '#EEF2FF', paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, alignSelf: 'flex-start', marginTop: 12 }, smallButtonText: { color: '#4338CA', fontWeight: '800', fontSize: 12 }, reportRow: { flexDirection: 'row', alignItems: 'baseline', gap: 8, borderBottomWidth: 1, borderColor: '#F1F5F9', paddingVertical: 8 }, reportNumber: { color: '#4F46E5', fontSize: 24, fontWeight: '800' }, empty: { color: '#64748B', marginBottom: 14 }, resetButton: { alignSelf: 'center', padding: 12, marginTop: 8 }, resetText: { color: '#64748B', fontWeight: '700', fontSize: 12, textDecorationLine: 'underline' },
});
